# Azure Pipeline for deploying to Azure Static Web Apps

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
  env:
    REACT_APP_API_URL: $(functionAppUrl)
    REACT_APP_FUNCTION_KEY: $(functionAppKey)
    REACT_APP_AZURE_AD_CLIENT_ID: $(azureAdClientId)
    REACT_APP_AZURE_AD_TENANT_ID: $(azureAdTenantId)

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'build'
    api_location: ''
    output_location: ''
    azure_static_web_apps_api_token: $(deploymentToken)
  displayName: 'Deploy to Azure Static Web Apps'
